accounts/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    # path('accounts/',include('django.contrib.auth.urls')),
    path('login/',views.LoginUser.as_view(),name='login'),
    path('logout/',views.LogoutUser.as_view(),name='logout'),
    path("register/",views.Register.as_view(), name="register"),
    path("profile/update/<int:pk>",views.UserProfileUpdate.as_view(), name="profile_update"),
        path("profile/<int:user_id>",views.user_profile, name="profile_user"),
    path('passwordchange/',views.Passwordchangeview.as_view(),name='passwordchange'),
    path("password_reset/", views.Password_Reset.as_view(), name="password_reset"),
    path("password_reset/done/",views.Password_Reset_Done.as_view(),name="password_reset_done"),
    path("reset/<uidb64>/<token>/",views.MyPasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path("reset/done/",views.MyPasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

social_website/urls.py
from django.contrib import admin
from django.urls import path,include
from social_app import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('social_app.urls')),
    path('accounts/',include('accounts.urls')),
    path('',views.home,name='home')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    image_profile=models.ImageField(upload_to='users_photo/',blank=True,null=True)
    cover_profile=models.ImageField(upload_to='users_photo/',blank=True,null=True)
    bio=models.TextField(max_length=160,blank=True,null=True)
    follow=models.ManyToManyField('self',through='Contact',related_name='followers',symmetrical=False)

class Contact(models.Model):
    user_to=models.ForeignKey(MyUser,on_delete=models.CASCADE,related_name='follow_to')
    user_from=models.ForeignKey(MyUser,on_delete=models.CASCADE,related_name='follow_from')
    created=models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=['-created']
        indexes=[
        models.Index(fields=['-created'])
        ]
        unique_together=('user_to','user_from')
        
    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'

accounts/forms.py
from django import forms
from accounts.models import MyUser as User
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
class LoginForm(AuthenticationForm):
    # remember_me=forms.BooleanField(required=False,label='remember_me',widget=forms.CheckboxInput())
    username=forms.CharField(label='Username or Email',required=True)
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        fields=['username','password']



class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']
        error_messages={'email':{'required':'This field is required .'}}        

    def clean_password2(self):
        password1=self.cleaned_data['password1']
        password2=self.cleaned_data['password2']
        if password1 != password2:
            raise forms.ValidationError('Passwords don\'t match.')
        return password2


    def clean_email(self):
        input_email=self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=input_email)
        if qs.exists():
            raise forms.ValidationError('%(value)s already in use.',params={'value':input_email})
        return input_email

        
class UpdateProfileUser(forms.ModelForm):
    # image_profile=forms.ImageField(required=False)
    # cover_profile=forms.ImageField(required=False)
    
    class Meta:
        model=User
        fields=['username','email','image_profile','cover_profile','bio']
        widgets={'bio':forms.Textarea(attrs={'rows':5})}

accounts/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.contrib.auth.views import LoginView,LogoutView,PasswordChangeView,PasswordChangeDoneView,\
    PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
from .forms import LoginForm,RegisterForm,UpdateProfileUser
from django.views.generic import CreateView,UpdateView
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from accounts.models import MyUser as User
from social_app.models import Post
from.models import Contact
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
# Create your views here.
from django.contrib.sites.shortcuts import get_current_site  
from django.utils.encoding import force_bytes
from social_app.forms import PostModelForm
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.template.loader import render_to_string  
from .tokens import account_activation_token  
from django.core.mail import EmailMessage  





class LoginUser(LoginView):
    template_name='accounts/login.html'
    form_class=LoginForm

    def form_valid(self, form):
        remember_me=form.cleaned_data.get('remember_me')
        if not remember_me:
            self.request.session.set_expiry(0)
        return super(LoginUser,self).form_valid(form)
    

class LogoutUser(LogoutView):
    template_name='accounts/logout.html'
class Register(CreateView):
    template_name='accounts/register.html'
    form_class=RegisterForm
    success_url=reverse_lazy('login')
    def form_valid(self, form):
        user =form.save(commit=False)  
        user.is_active = False  
        user.save()  
        # to get the domain of the current site  
        current_site = get_current_site(self.request)  
        mail_subject = 'Activation link has been sent to your email id'  
        message = render_to_string('accounts/acc_active_email.html', {  
                'user': user,  
                'domain': current_site.domain,  
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),  
                'token':account_activation_token.make_token(user),  
            })  
        to_email = form.cleaned_data.get('email')  
        email = EmailMessage(  
                        mail_subject, message, to=[to_email]  
            )  
        email.send()  
        return self.get_success_url()

    def get_success_url(self):
        return HttpResponse('Please confirm your email address to complete the registration')  
def activate(request, uidb64, token):   
    try:  
        uid = force_bytes(urlsafe_base64_decode(uidb64))  
        user = User.objects.get(pk=uid)  
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):  
        user = None  
    if user is not None and account_activation_token.check_token(user, token):  
        user.is_active = True  
        user.save()  
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.<a href="http://localhost:8000/accounts/login/"> Login</a>')  
    else:  
        return HttpResponse('Activation link is invalid!')  

@method_decorator(login_required,name='dispatch')
class UserProfileUpdate(UpdateView):
    model=User
    template_name='accounts/profile.html'
    form_class=UpdateProfileUser
    success_url=reverse_lazy('home')
    def form_valid(self, form):
        messages.add_message(self.request,messages.SUCCESS,"Your Profile update successfully")
        return super().form_valid(form)

@login_required
def user_profile(request,user_id):
    posts=Post.objects.filter(user__id=user_id)
    user_detail=User.objects.get(id=user_id)
    followers_count=Contact.objects.filter(user_to=user_detail).count()
    form=PostModelForm()



    followers=Contact.objects.filter(user_from=request.user).values('user_to_id')
    arr_id=[i['user_to_id'] for i in followers]
    follow=False
    if user_id in arr_id:
        follow=True
  
    arr_id.append(request.user.id)
    suggestion=Contact.objects.filter(user_from__in=arr_id).exclude(user_to__in=arr_id).order_by('?')[:5]
    return render(request,'accounts/profile_user.html',{'form':form,'posts':posts,'user':user_detail,'followers':followers_count,'suggestion':suggestion,'follow':follow})
    

    

class Passwordchangeview(PasswordChangeView):
    template_name='accounts/passwordchange.html'
    success_url=reverse_lazy('home')
    def form_valid(self, form):
        messages.add_message(self.request,messages.SUCCESS,"Your password changed successfully")
        return super().form_valid(form)
    

class Password_Reset(PasswordResetView):
    template_name='accounts/passwordreset.html'

class Password_Reset_Done(PasswordResetDoneView):
    template_name='accounts/passwordresetdone.html'

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    template_name='accounts/passwordresetconfirm.html'

class MyPasswordResetCompleteView(PasswordResetCompleteView):
    template_name='accounts/passwordresetcomplete.html'

templates/accounts/acc_active_email.html
Hi {{user.username }},  
Please click on the link to confirm your registration,  
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}  

templates/accounts/login.html
{% extends 'index.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    {{ block.super }}- Login
{% endblock title %}

{% block content %}
<div class="base_container">
    <div class="pages ">
        <div class="second_page">
            <div class="content">
                <img src="{% static 'images/undraw_people_search_re_5rre.svg' %}" alt="undraw_welcoming_re_x0qo">

                <h3>Meet Awesome People & Enjoy Yourself</h3>
                <p>Find friends on social platform ipsum dolor sit amet consectetur adipiscing elit</p>
                <a href="#" class="skip">Skip</a>
                <button class="next">Next</button>
                <div class="progress">
                </div>
            </div>
        </div>
        <div class="first_page">
            <div class="content">
                <img src="{% static 'images/undraw_welcoming_re_x0qo.svg' %}" alt="undraw_welcoming_re_x0qo">

                <h3>Find Friends & Get inspiration</h3>
                <p>Find friends on social platform ipsum dolor sit amet consectetur adipiscing elit</p>
                <a href="#" class="skip">Skip</a>
                <button class="next">Next</button>
                <div class="progress">

                </div>

            </div>
        </div>
        <div class="third_page ">
            <div class="content">
                <h1>Sign In Now</h1>
                <p>please enter your information below in order to login to your account .</p>
                <form action=""  method="post" novalidate autocomplete="off" >
                    
                     {% csrf_token %}
                    {% if form.non_field_errors %}
                    <div class="alert_danger">
                        {% for error in form.non_field_errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                    {% endif %} 
                    
                    {% for field in form  %}
                        <div class="form_control">
                        {% if form.is_bound %}
                            {% if field.errors %}
                                {% render_field field class="invalid" %}
                                {% for error in field.errors %}
                                    <p class="error" >{{error}}</p>
                                {% endfor %}
                            {% else %}
                            {% render_field field class="valid" %}

                            {% endif %}

                        {% else %}
                            {% render_field field  %}
                        {% endif %}
                        <label for="{{field.id_for_label}}">{{field.label}}</label>

                        
                        {% if forloop.last %}
                        <img src="{% static 'images/icons8-hide-30.png' %}" alt="icons8-hide-30.png" class="hide_show">
                        {% endif %}
                            
   
                        </div>

                    {% endfor %} 

                    <a href="{% url 'password_reset' %}" class="forgot-password">Forgot Password ?</a>
                    <input type="submit" value="Sign In">
                    <p class="form_ques"> Don't have an account ? <a href="{% url 'register' %}">Sign Up</a></p>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock content %}
    
    

templates/accounts/logout.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    {{ block.super }}-Logout
{% endblock title %}


{% block content %}
<div class="base_container">
    <div class="content">
        <img src="{% static 'images/undraw_welcoming_re_x0qo.svg' %}" >
        <h4 class="mt-5">Logged out</h4>

        <p>
            Thanks for spending some quality time with the site today.
        </p>
        <a href="{% url 'login' %}" style="text-decoration: underline; color: #5C7CFA; font-size: 14px;">Log in again</a>
        
    </div>


</div>
{% endblock content %}
    
    

templates/accounts/passwordchange.html
{% extends 'index.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    {{ block.super }}-Password-Change
{% endblock title %}

{% block content %}
<div class="base_container">
    <div class="content">
        
        <h4 class="mb-4">Password Change</h4>
        <form action="" method="post" novalidate autocomplete="off">
                   
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert_danger">
                {% for error in form.non_field_errors %}
                <span >{{error}}</span>
                {% endfor %}
            </div>
            {% endif %} 
            
            {% for field in form  %}
                <div class="form_control">
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="invalid" %}
                        {% for error in field.errors %}
                            <p class="error">{{error}}</p>
                        {% endfor %}
                    {% else %}
                    {% render_field field class="valid" %}

                    {% endif %}

                {% else %}
                    {% render_field field  %}
                {% endif %}
                <label for="{{field.id_for_label}}">{{field.label}}</label>

                
                {% if field.name == "new_password1" or field.name == "new_password2" or field.name == "old_password" %}
                <img src="{% static 'images/icons8-hide-30.png' %}" alt="icons8-hide-30.png" class="hide_show">

                {% endif %}
                    

                </div>

            {% endfor %} 
                


            <input type="submit" value="Reset Password">
        </form>
        <p class="form_cancel"><a href="{% url 'home' %}">Cancel</a></p>
    </div>

</div>
{% endblock content %}
    
    

templates/accounts/passwordreset.html
{% extends 'index.html' %}
{% load widget_tweaks %}
{% load static %}


{% block title %}
    {{ block.super }}- Password-Reset
{% endblock title %}

{% block content %}
<div class="base_container">
    <div class="content">
        <h1>Forgot Password</h1>
        <p>please enter your information below in order to create your account .</p>
        <form action="" method="post" novalidate autocomplete="off">

            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert_danger">
                {% for error in form.non_field_errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% endif %} 
            
            {% for field in form  %}
                <div class="form_control">
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="invalid" %}
                        {% for error in field.errors %}
                            <p class="error" >{{error}}</p>
                        {% endfor %}
                    {% else %}
                    {% render_field field class="valid" %}

                    {% endif %}

                {% else %}
                    {% render_field field  %}
                {% endif %}
                <label for="{{field.id_for_label}}">{{field.label}}</label>


                    

                </div>

            {% endfor %} 


            <input type="submit" value="Reset Password">
            <p class="form_cancel"><a href="{% url 'login' %}">Cancel</a></p>
        </form>
    </div>

</div>
{% endblock content %}
    
    

templates/accounts/passwordresetcomplete.html
{% extends 'index.html' %}

    {% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/passwordresetconfirm.html
{% extends 'index.html' %}
{% load widget_tweaks %}
{% load static %}
    {% block content %}

    <div class="base_container">
        <div class="content">
            <h4>Enter New Password</h4>
            <form action="" method="post" novalidate autocomplete="off">
                       
                {% csrf_token %}
                {% if form.non_field_errors %}
                <div class="alert_danger">
                    {% for error in form.non_field_errors %}
                    <span >{{error}}</span>
                    {% endfor %}
                </div>
                {% endif %} 
                
                {% for field in form  %}
                    <div class="form_control">
                    {% if form.is_bound %}
                        {% if field.errors %}
                            {% render_field field class="invalid" %}
                            {% for error in field.errors %}
                                <p class="error">{{error}}</p>
                            {% endfor %}
                        {% else %}
                        {% render_field field class="valid" %}
    
                        {% endif %}
    
                    {% else %}
                        {% render_field field  %}
                    {% endif %}
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
    
                    
                    {% if field.name == "password1" or field.name == "password2" %}
                    <img src="{% static 'images/icons8-hide-30.png' %}" alt="icons8-hide-30.png" class="hide_show">
    
                    {% endif %}
                        
    
                    </div>
    
                {% endfor %} 
                    
    
    
                <input type="submit" value="Reset Password">
            </form>
        </div>
    
    </div>
    {% endblock content %}
 

templates/accounts/passwordresetdone.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    {{ block.super }}-Password-reset-done
{% endblock title %}

{% block content %}
<div class="base_container d-flex justify-content-center align-items-center">
    <div class="content ">
        <img src="{% static 'images/undraw_confirmed_re_sef7.svg' %}" alt="" class="ms-5 mb-4">
        <h4 class="mb-4">Restore password</h4>

        <div>
            
            <p>We've emailed you instructions for setting your password, if an account exists with the email you entered .
            </p>
            <p>You should receive them shortly.</p>
            
            <p>If you don't receive an email, please make sure you've entered the address you signed up with, and check your spam folder.
            </p>
        </div>

    </div>

</div>
{% endblock content %}
    
    

templates/accounts/profile.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    {{ block.super }}
{% endblock title %}
    
{% block content %}
{% if messages %}
<div class="alert_success ">
    
    {% for message in messages %}
    <button class="close-alert" >X</button>
    <strong> Success !</strong> {{message}}
    {% endfor %}
</div>
{% endif %}
<body style=" background-color: rgb(1 4 8 / 4%);font-family: 'Poppins', sans-serif;">
    <div class="base">

        {% include 'social_app/aside-bar.html' %}

        
        <div class="inside-base">
            <main class="main profile">
                <div class="notific" >
                    <h5>Edit Profile</h5>
                    <div class="img-menu">
                        <img src="{% static 'images/icon-menu.svg' %}" alt="" class="menu">

                    </div>
                    
                </div>
          
                <form action="" method="post" autocomplete="off" enctype="multipart/form-data">
                   {% csrf_token %}
                    <div class="images">
                        
                        {% if request.user.cover_profile %}
                        <img src="{{request.user.cover_profile.url}}" alt="" class="image_cover">
                        {% else %}
                        <img src="{% static 'images/no_pic.png' %}" alt="" class="image_cover">
                        {% endif %}
                            
                        <label for="id_cover_profile"><svg width="1.1em" height="1.1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="#244dee" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z"></path>
                            <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z"></path>
                        </svg></label>
                       
                        <div class="input_hidden">
                            {{form.cover_profile}}
                        </div>
                        
                        {% if request.user.image_profile %}
                        <img src="{{request.user.image_profile.url}}" alt="" class="image_profile">
                        {% else %}
                        <img src="{% static 'images/no_pic.png' %}" alt="" class="image_profile">
                        {% endif %}
                        <label for="id_image_profile"><img src="{% static 'images/icons8-plus.svg' %}" alt=""></label>
                        <div class="input_hidden">
                            {{form.image_profile}}
                        </div>
                       
                    </div>
                    <div class="form-group">
                        <div>
                            <label for="username">{{form.username.label_tag}}</label>
                            {{form.username}}
                            {% comment %} <input type="text" name="username" id="username"> {% endcomment %}
                        </div>
                        <div>
                            <label for="email">{{form.email.label_tag}}</label>
                            {{form.email}}
                            {% comment %} <input type="email" name="email" id="email"> {% endcomment %}
                        </div>
                        <div class="bio">
                            <label for="bio">{{form.bio.label_tag}}</label>
                            {{form.bio}}
                            {% comment %} <textarea name="bio" id="bio" cols="30" rows="5"></textarea> {% endcomment %}
                        </div>
                    </div>

                    <div class="sub">
                        <button type="submit">Update</button>
                        
                        <a href="{% url 'profile_user' request.user.id %}" class="cancel"  >Cancel</a>
                    </div>



                </form>


                {% include 'social_app/footer.html' %}
            </main>

            {% include 'social_app/right_section.html' %}
        </div>
    
    </div>
</body>


    
{% endblock content %}














    
    

templates/accounts/register.html
{% extends 'index.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
    {{ block.super }}- SignUp
{% endblock title %}

{% block content %}
<div class="base_container">
    <div class="content">
        <h1>Sign Up</h1>
        <p>please enter your information below in order to create your account .</p>
        <form action="" method="post" novalidate autocomplete="off">
                   
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert_danger">
                {% for error in form.non_field_errors %}
                <span >{{error}}</span>
                {% endfor %}
            </div>
            {% endif %} 
            
            {% for field in form  %}
                <div class="form_control">
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="invalid" %}
                        {% for error in field.errors %}
                            <p class="error">{{error}}</p>
                        {% endfor %}
                    {% else %}
                    {% render_field field class="valid" %}

                    {% endif %}

                {% else %}
                    {% render_field field  %}
                {% endif %}
                <label for="{{field.id_for_label}}">{{field.label}}</label>

                
                {% if field.name == "password1" or field.name == "password2" %}
                <img src="{% static 'images/icons8-hide-30.png' %}" alt="icons8-hide-30.png" class="hide_show">

                {% endif %}
                    

                </div>

            {% endfor %} 
                


            <input type="submit" value="Sign Up">
            <p class="form_ques">Already have an account ? <a href="{% url 'login' %}">Sign In</a></p>
        </form>
    </div>

</div>
{% endblock content %}
    
    